sudo: required
dist: trusty
language: python
python:
  - "3.5"
before_install:
  - cd ..
  - git clone https://github.com/sonata-nfv/son-cli
  - cd son-cli
  - python setup.py build
  - python setup.py install
  - cd ../upb-son-editor-backend
install:
  - "python setup.py install"
script:
  - "python setup.py test"
