language: python
python:
  - "3.5"
before_install:
  - pip install git+https://github.com/CN-UPB/son-cli.git@v2.0
  - pip install codecov
install:
  - "python setup.py install"
script:
  - "codecov run setup.py test"
