authentication:
    ClientID: 54e6b84b3eb8f6a460bc
    ClientSecret: ed068143acd3bbe0d9f9b76fcafedf652d63b807


session:
    secretKey: randomSecretKeyHere

frontend-redirect: "/src/loginRedirect.html"
frontend-host: "http://localhost:5000"

workspaces-location: "~/son-editor/workspaces/"

allowed-hosts:
  - "localhost"
  - "fg-cn-sandman1.cs.upb.de"
  - "cn-upb.github.io"
database:
    location: "production.db"

schemas:
  vnf:
    - https://raw.githubusercontent.com/sonata-nfv/son-schema/master/function-descriptor/vnfd-schema.yml
  ns:
    - https://raw.githubusercontent.com/sonata-nfv/son-schema/master/service-descriptor/nsd-schema.yml
testing: False
