authentication:
    ClientID: 54e6b84b3eb8f6a460bc
    ClientSecret: 789d0a5650b62c47ad72d6fcae876dc5461634ef


session:
    secretKey: randomSecretKeyHere

frontend-redirect: "/src/loginRedirect.html"
frontend-host: "http://localhost:5000"

workspaces-location: "~/son-editor/workspaces/"

allowed-hosts:
  - "localhost"
  - "fg-cn-sandman1.cs.upb.de"
  - "cn-upb.github.io"
database:
    location: "production.db"



github_bot_user: "pgsandmanbot"
github_access_token: f7ec6e61e6a265f3e009947305995942d0a5ebac


schemas:
  vnf:
    - https://raw.githubusercontent.com/sonata-nfv/son-schema/master/function-descriptor/vnfd-schema.yml
  ns:
    - https://raw.githubusercontent.com/sonata-nfv/son-schema/master/service-descriptor/nsd-schema.yml
testing: False
