authentication:
    ClientID: 54e6b84b3eb8f6a460bc
    ClientSecret: 277c00823cf9f3795e01ed6cd79ae1269aaf9844


session:
    secretKey: randomSecretKeyHere

frontend-redirect: "/src/loginRedirect.html"
frontend-host: "http://localhost:5000"

workspaces-location: "~/son-editor/workspaces/"

allowed-hosts:
  - "localhost"
  - "fg-cn-sandman1.cs.upb.de"
  - "cn-upb.github.io"
database:
    location: "production.db"

schemas:
  vnf:
    - https://raw.githubusercontent.com/sonata-nfv/son-schema/master/function-descriptor/vnfd-schema.yml
  ns:
    - https://raw.githubusercontent.com/sonata-nfv/son-schema/master/service-descriptor/nsd-schema.yml
testing: False

config:
  pwd: totes-secret
  user: admin

test:
  test-platform: "http://fg-cn-sandman2.cs.upb.de:1234"
  wrong-test-platform: "http://fg-cn-sandman2.cs.upb.de:1010"


#github-orgs:
#  - CN-UPB