authentication:
    ClientID: 9d6665533bcf1495e986
    ClientSecret: fe046449c98c89606e16ae3fd7126f09962b22cf


session:
    secretKey: randomSecretKeyHere

frontend-redirect: "/src/loginRedirect.html"
frontend-host: "http://jonas-msi:8000"

workspaces-location: "~/son-editor/workspaces/"

allowed-hosts:
  - "localhost"
  - "fg-cn-sandman1.cs.upb.de"
database:
    location: "production.db"
testing: False
