# GitHub OAuth configuration
authentication:
    ClientID: 54e6b84b3eb8f6a460bc
    ClientSecret: 277c00823cf9f3795e01ed6cd79ae1269aaf9844
    users:
      - user1
      - user2

#uncomment and configure to persist sessions across restarts
#session:
#    secretKey: randomSecretKeyHere

frontend-redirect: "/src/loginRedirect.html"
frontend-host: "http://localhost:5000"

# Workspace location, where user related data (e.g. projects) get saved.
workspaces-location: "~/son-editor/workspaces/"

# Hosts that are able to access the server
allowed-hosts:
  - "localhost"
  - "fg-cn-sandman1.cs.upb.de"
  - "cn-upb.github.io"

# Database file name
database:
    location: "production.db"

# URL to sonata schemas
schemas:
  vnf:
    - url: https://raw.githubusercontent.com/CN-UPB/son-schema/master/function-descriptor/vnfd-schema.yml
      name: CN-UPB VNFD
    - url: https://raw.githubusercontent.com/sonata-nfv/son-schema/master/function-descriptor/vnfd-schema.yml
      name: SONATA NFV VNFD
  ns:
    - url: https://raw.githubusercontent.com/CN-UPB/son-schema/master/service-descriptor/nsd-schema.yml
      name: CN-UPB NSD
    - url: https://raw.githubusercontent.com/sonata-nfv/son-schema/master/service-descriptor/nsd-schema.yml
      name: SONATA NFV NSD
testing: False

#uncomment and configure to enable web configuration
#config:
#  pwd: totes-secret
#  user: admin

# Test configuration
test:
  # Running sonata platform url
  platform-instance: "http://fg-cn-sandman2.cs.upb.de:1234"
  # Running sonata platform url with wrong port
  platform-instance-wrong: "http://fg-cn-sandman2.cs.upb.de:1010"
  # son-catalogue instance
  catalogue-instance: "http://fg-cn-sandman2.cs.upb.de:4012"
  # Github test-account information
  github:
    user: "user"
    access-token: token
