authentication:
    ClientID: 54e6b84b3eb8f6a460bc
    ClientSecret: 277c00823cf9f3795e01ed6cd79ae1269aaf9844


session:
    secretKey: randomSecretKeyHere

frontend-redirect: "/src/loginRedirect.html"
frontend-host: "http://localhost:5000"

workspaces-location: "~/son-editor/workspaces/"

allowed-hosts:
  - "localhost"
  - "fg-cn-sandman1.cs.upb.de"
database:
    location: "production.db"
testing: False
